#include <stdio.h>
#include <stdlib.h>
#include "codegen.h"

/* regTop tracks the highest-numbered register currently allocated.
 * -1 means no register is in use. */
static int regTop = -1;

reg_index getReg(void) {
    regTop++;
    if (regTop >= NUM_REGS) {
        fprintf(stderr, "Error: Out of registers\n");
        exit(1);
    }
    return regTop;
}

void freeReg(void) {
    if (regTop < 0) {
        fprintf(stderr, "Error: freeReg() called with no register allocated\n");
        exit(1);
    }
    regTop--;
}

/*
 * codeGen(t, f):
 *   Leaf node (t->op == NULL)   -> allocate a new register, MOV the constant
 *                                  into it, return that register's index.
 *   Operator node (t->op != NULL)
 *        -> recursively generate code for the left subtree,  get reg p
 *        -> recursively generate code for the right subtree, get reg q
 *           (p is guaranteed < q by the allocation policy)
 *        -> ADD Rp, Rq   (result left in the lower register, p)
 *        -> freeReg()    (releases q, the higher register)
 *        -> return p
 */
reg_index codeGen(struct tnode *t, FILE *target_file) {
    if (t == NULL) {
        fprintf(stderr, "Error: codeGen called on NULL node\n");
        exit(1);
    }

    if (t->op == NULL) {
        reg_index r = getReg();
        fprintf(target_file, "MOV R%d, %d\n", r, t->val);
        return r;
    }

    reg_index p = codeGen(t->left, target_file);
    reg_index q = codeGen(t->right, target_file);

    /* Only '+' exists in this grammar; this switch is written so that
     * exercise 2 (adding -, *, /) only needs new cases here. */
    switch (t->op[0]) {
        case '+': fprintf(target_file, "ADD R%d, R%d\n", p, q); break;
        case '-': fprintf(target_file, "SUB R%d, R%d\n", p, q); break;
        case '*': fprintf(target_file, "MUL R%d, R%d\n", p, q); break;
        case '/': fprintf(target_file, "DIV R%d, R%d\n", p, q); break;
        default:
            fprintf(stderr, "Error: unknown operator '%s'\n", t->op);
            exit(1);
    }

    freeReg();   /* release the higher-numbered register, q */
    return p;    /* result lives in the lower-numbered register, p */
}

/*
 * generate_code(root, filename):
 *   Writes a complete XEXE file:
 *     - 8-word header (magic number 0, entry point 2056, rest 0)
 *     - code generated by codeGen() for the expression
 *     - MOV [4096], Rresult      (store the result in the stack region)
 *     - the write-system-call sequence (system-call interface, INT 7)
 *       that prints the value in Rresult to the console
 */
void generate_code(struct tnode *root, const char *filename) {
    FILE *target_file = fopen(filename, "w");
    if (target_file == NULL) {
        fprintf(stderr, "Error: could not open '%s' for writing\n", filename);
        exit(1);
    }

    /* --- XEXE header: 8 words --- */
    
    fprintf(target_file, "%d\n%d\n%d\n%d\n%d\n%d\n%d\n%d\n", 0, 2056, 0, 0, 0, 0, 0, 0);

    /* --- Expression evaluation --- */
    reg_index result = codeGen(root, target_file);
    

    /* store the result at memory address 4096 --- */
    fprintf(target_file, "MOV [4096], R%d\n", result);

    /* --- Print the result using the write system call --- */
    fprintf(target_file, "MOV SP, 4095\n");

    reg_index sysno = getReg();          /* fresh temp register for syscall setup */
    fprintf(target_file, "MOV R%d, 5\n", sysno);     /* 5 = write system call number */
    fprintf(target_file, "PUSH R%d\n", sysno);

    reg_index blank = getReg();          /* reused for arg1 and the two blank slots */
    fprintf(target_file, "MOV R%d, -2\n", blank);    /* argument 1: -2 (console) */
    fprintf(target_file, "PUSH R%d\n", blank);

    fprintf(target_file, "PUSH R%d\n", result);      /* argument 2: value to print */

    fprintf(target_file, "PUSH R%d\n", blank);       /* argument 3: blank */
    fprintf(target_file, "PUSH R%d\n", blank);        /* space for return value */

    fprintf(target_file, "INT 7\n");                  /* interrupt 7 = write syscall */

    /* Unwind the stack in reverse order of the pushes above */
    fprintf(target_file, "POP R%d\n", result);        /* save return value (unused) */
    fprintf(target_file, "POP R%d\n", blank);
    fprintf(target_file, "POP R%d\n", blank);
    fprintf(target_file, "POP R%d\n", blank);
    fprintf(target_file, "POP R%d\n", sysno);

    freeReg(); /* blank */
    freeReg(); /* sysno */

    fclose(target_file);
}